### ISSUE TITLE
Page type 404 does not work if rootcontent is installed

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-rootcontent#2]
I asume it worked before but since i updated contao to 4.8.4 the page-not-found page no longer works I'll be presented the /symfony/twig-bundle/Resources/views/Exception/error.html.twig message instead.
[Forumpost](https://community.contao.org/de/showthread.php?76129-404-Seiten)

**Comment by aschempp** [comment]
How is this related to this extension?

**Comment by asaage** [comment]
I don't know how or why.
I narrowed it down by making a basic 4.8.4 install where the error-page (contao-pagetype-404) worked - then installed this extension and it didnt't work anymore. Multiple installations show the same symptoms when i uninstall rootcontent the error page works again.
Let me know what kind of information you would need to reproduce.

**Comment by aschempp** [comment]
@qzminski can you please try to reproduce this? It would be an issue for all our clients as well 🙃

**Comment by qzminski** [comment]
I am not unable to reproduce the issue. Here is my setup:

```
Website root
– Page not found 404
– Home
```

When I access the `foobar.html` URL it shows me the "Page not found 404" page with my custom content:

![2019-10-31 at 14 06](https://user-images.githubusercontent.com/193483/67949255-b7baca80-fbe7-11e9-8afe-abde423e9c40.png)

**Comment by asaage** [comment]
Honestly i can not reproduce it myself now anymore. I did a fresh installation with rootcontent and everything works as expected 
and in the Installation that has this error now i can't get rid of it by uninstalling rootcontent.
Therefore i'm closing this.
Unfortunately i have no clue how to debug this... 🤔
